// <auto-generated />
using System;
using BasicSecurityProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicSecurityProject.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20190328153658_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicSecurityProject.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hash");

                    b.Property<byte[]>("PrivateKey");

                    b.Property<byte[]>("PublicKey");

                    b.Property<string>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Hash = "A8CFCD74832004951B4408CDB0A5DBCD8C7E52D43F7FE244BF720582E05241DA",
                            Salt = "ef6e5f49d8ssd8v",
                            Username = "John"
                        },
                        new
                        {
                            ID = 2,
                            Hash = "9AE4BC0E32DB0E3484CD398459D20F9B4F79CCE36667428181BF037131A3C987",
                            Salt = "ef6e5f49d8ssd8v",
                            Username = "Chris"
                        },
                        new
                        {
                            ID = 3,
                            Hash = "E2674AA2162A3225B5B51DD0A796C32F17679642593347BD6A24EB90EEBF912B",
                            Salt = "ef6e5f49d8ssd8v",
                            Username = "Mukesh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
